service: blog-man
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  home:
    handler: handler.home
    events:
      - httpApi:
          path: /
          method: get

  posts:
    handler: modules/post/index.posts
    events:
      - httpApi:
          path: /posts
          method: get
plugins:
  - serverless-offline
  - serverless-dotenv-plugin

# only include the Prisma binary required on AWS Lambda while packaging
package:
  patterns:
    - '!node_modules/.prisma/client/libquery_engine-*'
    - 'node_modules/.prisma/client/libquery_engine-rhel-*'
    - '!node_modules/prisma/libquery_engine-*'
    - '!node_modules/@prisma/engines/**'
