service: blog-man
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x

functions:
  home:
    handler: handler.home
    events:
      - httpApi:
          path: /
          method: get

plugins:
  - serverless-offline
